name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    # - cron: '4 14 * * 3'
      - cron: '* * * * *'

jobs:
  scheduled:
   runs-on: ubuntu-latest
   steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; 

    - name: Execute script
      run: python vwu_scraper.py

    - name: Commit files
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
